### CREATE
POST http://localhost:8080/api/clients/create
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Testowy",
  "pesel" : "77093012345",
  "email" : "tt@op.pl",
  "address" : "Warszawa",
  "phoneNumber" : 600800780

}
### READ client with products and their details' history
GET http://localhost:8080/api/clients/1/products/details/

### READ only data client
GET http://localhost:8080/api/clients/1

### UPDATE
PUT http://localhost:8080/api/clients/update/6
Content-Type: application/json

{
  "id": 6,
  "firstName": "Test",
  "lastName": "Testowy",
  "pesel" : "77093012345",
  "email" : "tt@op.pl",
  "address" : "CHICAGO",
  "phoneNumber" : 600800780
}

### DELETE
DELETE http://localhost:8080/api/clients/del/5