### ADD
POST http://localhost:8080//api/types
Content-Type: application/json

{
  "productType": "P1",
  "productName": "Name1",
  "creationDate" : "2023-05-07"

}

### UPDATE
PUT http://localhost:8080/api/types/5
Content-Type: application/json

{
  "id": 5,
  "productType": "P1",
  "productName": "Name1"
}
