### ADD
POST http://localhost:8080//api/types
Content-Type: application/json

{
  "productType": "T",
  "productName": "Test",
  "creationDate" : "2023-05-10"

}

### UPDATE
PUT http://localhost:8080/api/types/5
Content-Type: application/json

{
  "id": 5,
  "productType": "chan",
  "productName": "changed",
  "creationDate" : "2023-05-10"
}
